# Secrets Management Configuration

# Vault Configuration
vault:
  type: hashicorp
  address: "https://vault.internal:8200"
  
  auth:
    method: kubernetes
    role: payment-gateway
    mount_path: auth/kubernetes
    
  ha:
    enabled: true
    replicas: 3
    retry_join:
      - "vault-0.vault-internal:8201"
      - "vault-1.vault-internal:8201"
      - "vault-2.vault-internal:8201"

# Secret Paths
paths:
  hsm:
    path: "secret/hsm"
    keys:
      - "primary_credentials"
      - "secondary_credentials"
      - "backup_credentials"
  
  database:
    path: "secret/database"
    keys:
      - "primary_credentials"
      - "replica_credentials"
      - "admin_credentials"
  
  api:
    path: "secret/api"
    keys:
      - "jwt_private_key"
      - "jwt_public_key"
      - "webhook_secrets"
  
  ssl:
    path: "secret/ssl"
    keys:
      - "private_key"
      - "certificate"
      - "ca_bundle"

# Access Control
access_control:
  roles:
    admin:
      capabilities:
        - read
        - write
        - delete
        - list
      paths:
        - "secret/*"
    
    application:
      capabilities:
        - read
      paths:
        - "secret/hsm/primary_credentials"
        - "secret/database/primary_credentials"
        - "secret/api/*"
    
    monitoring:
      capabilities:
        - read
      paths:
        - "secret/monitoring/*"

# Key Rotation
key_rotation:
  schedules:
    hsm_credentials:
      interval: 90d
      notification: 7d
    
    database_credentials:
      interval: 30d
      notification: 3d
    
    jwt_keys:
      interval: 180d
      notification: 14d
    
    ssl_certificates:
      interval: 365d
      notification: 30d

# Encryption
encryption:
  transit:
    enabled: true
    key_type: aes256-gcm96
    rotation_period: 90d
    
  kms:
    provider: aws
    region: us-west-2
    key_id: "arn:aws:kms:us-west-2:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab"

# Audit
audit:
  enabled: true
  sinks:
    file:
      path: "/var/log/vault/audit.log"
      mode: 0600
    
    syslog:
      enabled: true
      facility: AUTH
      tag: vault-audit

# Recovery
recovery:
  keys:
    shares: 5
    threshold: 3
    
  stored_shares:
    enabled: true
    pgp_keys:
      - "keybase:security_officer_1"
      - "keybase:security_officer_2"
      - "keybase:security_officer_3"
      - "keybase:security_officer_4"
      - "keybase:security_officer_5"

# Monitoring
monitoring:
  enabled: true
  metrics:
    enabled: true
    retention: 30d
    
  alerts:
    - name: vault_seal_status
      description: "Vault seal status changed"
      severity: critical
      
    - name: vault_token_expiry
      description: "Service tokens nearing expiry"
      severity: warning
      threshold: 7d
